---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - kzzy
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kzzy
  resources:
  - jobs/status
  verbs:
  - get
- apiGroups:
  - webapp.kzzy
  resources:
  - clusterscans
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.kzzy
  resources:
  - clusterscans/finalizers
  verbs:
  - update
- apiGroups:
  - webapp.kzzy
  resources:
  - clusterscans/status
  verbs:
  - get
  - patch
  - update
